# Generated by Django 5.0.6 on 2024-07-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=100, verbose_name='delivery_name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Maximum 999.99', max_digits=5, verbose_name='delivery_price')),
                ('method', models.CharField(choices=[('STD', 'Standard Delivery'), ('EXP', 'Express Delivery'), ('SDD', 'Same Day Delivery'), ('NDD', 'Next Day Delivery')], default='STD', max_length=100, verbose_name='delivery_method')),
                ('delivery_time', models.CharField(help_text='Required', max_length=150, verbose_name='delivery_time')),
                ('delivery_window', models.CharField(help_text='Required', max_length=255, verbose_name='delivery_window')),
                ('order', models.IntegerField(default=0, help_text='Required', verbose_name='list_order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Option',
                'verbose_name_plural': 'Delivery Options',
            },
        ),
    ]
